// web-angular/src/app/components/message-list.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import type { TurnItem } from '../core/turn-item.type';
import { Message } from './message';

// Port of web-react/src/components/MessageList.tsx
@Component({
  selector: 'app-message-list',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [Message],
  template: `
    <div class="space-y-5">
      @for (item of renderLog(); track item.id) {
        <app-message [item]="item" />
      }
    </div>
  `,
})
export class MessageList {
  readonly renderLog = input.required<TurnItem[]>();
}

// web/src/components/MessageList.tsx
import type { TurnItem } from '../App';
import Message from './Message';

export default function MessageList({ renderLog }: { renderLog: TurnItem[] }) {
  return (
    <div className="space-y-5">
      {renderLog.map((item) => (
        <Message key={item.id} item={item} />
      ))}
    </div>
  );
}
